FROM bcgovimages/aries-cloudagent:py36-1.15-0_0.5.4

#COPY ./message_families .
#RUN pip install ./audit_proof
RUN pip3 install --no-cache-dir "git+https://github.com/ianco/aca-py-audit-plugin.git@master#egg=subdir&subdirectory=message_families/audit_proof"

ENTRYPOINT ["/bin/bash", "-c", "aca-py \"$@\"", "--"]
